# Generated by Django 3.1.3 on 2025-10-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedReport',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('fullname', models.CharField(max_length=50, verbose_name='Enter Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Enter Phone Number')),
                ('gender', models.CharField(max_length=10, verbose_name='Enter Gender')),
                ('age', models.IntegerField(verbose_name='Enter Age')),
                ('img', models.ImageField(upload_to='images/')),
                ('test_type', models.CharField(max_length=50, verbose_name='Test Type')),
                ('results', models.CharField(max_length=50, verbose_name='Prediction Results')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
